server:
  port: 8395

spring:
  datasource:
    driverClassName: "net.sf.log4jdbc.sql.jdbcapi.DriverSpy"
    url: "jdbc:log4jdbc:h2:mem:test"
    username: "sa"
    password: ""
  h2:
    console:
      enable: true
      path: "/h2"
  devtools:
    livereload:
      enabled: true
  sql:
    init:
      schema-locations: "classpath:schema.sql"
      mode: never

logging:
  level:
    root: "info"
    org.springframework: "info"
